"""Turn the server's ``server-info.json`` into importable client profiles.

Deliberately emitters, not templates: JSON via ``json.dumps`` and the mihomo
config as a hand-written block —— no template engine, so the tool stays
stdlib-only and the output is diffable.
"""

from __future__ import annotations

import base64
import json
import os
from typing import Any
from urllib.parse import quote

from . import state

PROFILE_FILES = (
    "vless-link.txt",
    "v2rayng-subscription.txt",
    "mihomo.yaml",
    "singbox.json",
    "README.txt",
)

# --------------------------------------------------------------------------
# 分流规则
#
# 三层，**顺序不能乱**：先把"肯定不该出去的"摘掉 → 再判断国内/国外 → 最后兜底。
# 写反了就会出现"访问 NAS 绕到香港去"这种问题。
# --------------------------------------------------------------------------

# 局域网与本机地址，必须**自己列出来**。
# GEOIP 对私有地址返回空，只靠 `GEOIP,CN` 兜不住：这些流量会落到最后的
# MATCH,PROXY，于是访问 NAS / 打印机 / 路由器管理页要绕到香港再回来——
# 结果是打不开，而且把内网地址暴露给了代理。
_DIRECT_CIDRS = (
    "127.0.0.0/8",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "100.64.0.0/10",  # 运营商级 NAT
    "169.254.0.0/16",  # link-local
    "224.0.0.0/4",  # 组播
)
_DIRECT_CIDRS6 = ("fc00::/7", "fe80::/10")

# 联网探测类域名。这些走了代理，系统会以为"连上了但没有互联网"，
# 或者在 Wi-Fi 里弹一个莫名其妙的警告。固定直连。
_PROBE_DOMAINS = (
    "msftconnecttest.com",
    "msftncsi.com",
    "captive.apple.com",
    "connectivitycheck.gstatic.com",
)

# fake-ip 会给每个域名发一个 198.18.x.x 的假地址。局域网名字解析
# （Bonjour / mDNS / 路由器发的 .lan）必须绕开它，否则 AirDrop、
# 打印机、投屏会突然找不到设备——而用户完全不会想到是代理干的。
_FAKE_IP_FILTER = (
    "*.lan",
    "*.local",
    "*.localhost",
    "+.msftconnecttest.com",
    "+.msftncsi.com",
)


def _domain_rules(domains) -> list[str]:
    """把域名后缀列表变成 DOMAIN-SUFFIX 规则，顺手去重、归一化。"""
    seen: set[str] = set()
    rules: list[str] = []
    for raw in domains or ():
        domain = str(raw).strip().lower().lstrip(".")
        if not domain or domain in seen:
            continue
        seen.add(domain)
        rules.append(f"  - DOMAIN-SUFFIX,{domain},DIRECT")
    return rules


def mihomo_rules(direct_domains=None) -> list[str]:
    """生成 mihomo 的 rules 段。抽出来是为了能被单独测试。
    `direct_domains` 为 None 时用内置名单；传空列表就是"不要额外直连域名"。
    """
    if direct_domains is None:
        direct_domains = state.DEFAULT_DIRECT_DOMAINS
    rules = [f"  - IP-CIDR,{c},DIRECT,no-resolve" for c in _DIRECT_CIDRS]
    rules += [f"  - IP-CIDR6,{c},DIRECT,no-resolve" for c in _DIRECT_CIDRS6]
    rules += [f"  - DOMAIN-SUFFIX,{d},DIRECT" for d in _PROBE_DOMAINS]
    rules.append("  - DOMAIN-SUFFIX,cn,DIRECT")
    rules += _domain_rules(direct_domains)
    rules.append("  - GEOIP,CN,DIRECT")
    rules.append("  - MATCH,PROXY")
    return rules


def build_link(info: dict[str, Any], label: str = "HK-Spot") -> str:
    params = [
        ("encryption", "none"),
        ("flow", info.get("flow") or ""),
        ("security", info.get("security") or "reality"),
        ("sni", info.get("sni") or "www.microsoft.com"),
        ("fp", info.get("fingerprint") or "chrome"),
        ("pbk", info["public_key"]),
        ("sid", info.get("short_id") or ""),
        ("type", info.get("transport") or "tcp"),
        ("headerType", "none"),
    ]
    pairs = ["{}={}".format(key, quote(str(value), safe="")) for key, value in params if value != ""]
    return "vless://{}@{}:{}?{}#{}".format(
        info["uuid"],
        info["address"],
        int(info["port"]),
        "&".join(pairs),
        quote(label, safe=""),
    )


def subscription_blob(links: list[str]) -> str:
    """v2rayNG/Clash style subscription payload: base64 of newline-joined links."""
    return base64.b64encode(("\n".join(links) + "\n").encode("utf-8")).decode("ascii")


def render_mihomo(
    info: dict[str, Any],
    label: str = "HK-Spot",
    mixed_port: int = 7890,
    external_controller: str = "",
    controller_socket: str = "",
    direct_domains=None,
) -> str:
    rules = "\n".join(mihomo_rules(direct_domains))
    fake_ip_filter = "\n".join(f"    - '{p}'" for p in _FAKE_IP_FILTER)
    # 控制接口两个都是可选的（命令行用 unix socket，独立客户端可能要 http）。
    # 拼成一块再插进去，避免为空时在文件里留下多余空行。
    controller_lines = []
    if external_controller:
        controller_lines.append(f"external-controller: {external_controller}")
    if controller_socket:
        controller_lines.append(f"external-controller-unix: {controller_socket}")
    controller_block = ("\n".join(controller_lines) + "\n") if controller_lines else ""
    return """# generated by yi - Clash Verge Rev / mihomo
# 分流策略：局域网与本机直连 → 国内域名直连 → GEOIP 判断 → 其余走代理。
# 改动规则请改 src/yi/configgen.py 的 mihomo_rules()，不要手改这个文件
# （下次 `yi sub` 会覆盖它）。
mixed-port: {mixed_port}
allow-lan: false
mode: rule
log-level: info
ipv6: false
unified-delay: true
tcp-concurrent: true
{controller_block}
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
{fake_ip_filter}
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN

proxies:
  - name: "{label}"
    type: vless
    server: {address}
    port: {port}
    uuid: {uuid}
    network: tcp
    tls: true
    udp: true
{flow_line}
    servername: {sni}
    client-fingerprint: {fingerprint}
    reality-opts:
      public-key: {public_key}
      short-id: "{short_id}"

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - "{label}"
      - DIRECT

rules:
{rules}
""".format(
        label=label,
        mixed_port=int(mixed_port),
        controller_block=controller_block,
        fake_ip_filter=fake_ip_filter,
        rules=rules,
        address=info["address"],
        port=int(info["port"]),
        uuid=info["uuid"],
        flow_line="    flow: {}".format(info["flow"]) if info.get("flow") else "",
        sni=info.get("sni") or "www.microsoft.com",
        fingerprint=info.get("fingerprint") or "chrome",
        public_key=info["public_key"],
        short_id=info.get("short_id") or "",
    )


def render_singbox(info: dict[str, Any], label: str = "HK-Spot") -> str:
    """sing-box 1.11+ schema (tun + mixed inbounds, VLESS/REALITY outbound)."""
    payload = {
        "log": {"level": "info", "timestamp": True},
        "dns": {
            "servers": [
                {"tag": "dns-remote", "address": "https://1.1.1.1/dns-query", "detour": "proxy"},
                {"tag": "dns-direct", "address": "223.5.5.5", "detour": "direct"},
            ],
            "rules": [{"ip_is_private": True, "server": "dns-direct"}],
        },
        "inbounds": [
            {
                "type": "tun",
                "tag": "tun-in",
                "address": ["172.19.0.1/30"],
                "mtu": 1500,
                "auto_route": True,
                "strict_route": True,
                "stack": "mixed",
                "sniff": True,
            },
            {
                "type": "mixed",
                "tag": "mixed-in",
                "listen": "127.0.0.1",
                "listen_port": 7891,
                "sniff": True,
            },
        ],
        "outbounds": [
            {
                "type": "vless",
                "tag": "proxy",
                "server": info["address"],
                "server_port": int(info["port"]),
                "uuid": info["uuid"],
                "packet_encoding": "xudp",
                "tls": {
                    "enabled": True,
                    "server_name": info.get("sni") or "www.microsoft.com",
                    "utls": {"enabled": True, "fingerprint": info.get("fingerprint") or "chrome"},
                    "reality": {
                        "enabled": True,
                        "public_key": info["public_key"],
                        "short_id": info.get("short_id") or "",
                    },
                },
            },
            {"type": "direct", "tag": "direct"},
        ],
        "route": {
            "rules": [
                {"action": "sniff"},
                {"protocol": "dns", "action": "hijack-dns"},
                {"ip_is_private": True, "outbound": "direct"},
            ],
            "final": "proxy",
            "auto_detect_interface": True,
        },
        "experimental": {"cache_file": {"enabled": True, "store_fakeip": True}},
    }
    if info.get("flow"):
        payload["outbounds"][0]["flow"] = info["flow"]
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def render_readme(info: dict[str, Any], label: str = "HK-Spot") -> str:
    return """yi 客户端配置说明
========================

服务端: {address}:{port}   (VLESS + XTLS-Vision + REALITY)
生成时间: {created}

凭据即密码：本目录下所有文件都等同于你的账号密码，不要发群里、不要传网盘。

---------------------------------------------------------------
Android（v2rayNG）
---------------------------------------------------------------
1. 安装 v2rayNG（GitHub: 2dust/v2rayNG）。
2. 方式 A（推荐）：打开 v2rayng-subscription.txt，把整段 base64 复制，
   在 v2rayNG 里点 "+" -> "从剪贴板导入"。
   方式 B：把 vless-link.txt 里那一行链接复制，选 "从剪贴板导入分享链接"。
   方式 C：扫描 yi 输出的二维码（需要本机有 qrencode 或 qrcode 包）。
3. 回到主界面点右下角连接，系统弹出 VPN 授权时允许。
4. 验证：浏览器打开 ipinfo.io，显示 Hong Kong 即为成功。

分应用代理：设置 -> 分应用代理，选择"绕过"或"仅代理"列表。

---------------------------------------------------------------
macOS（Clash Verge Rev，推荐）
---------------------------------------------------------------
1. 安装 Clash Verge Rev。左侧菜单里那一页叫「订阅」，不叫「配置」。
2. 订阅页右上角有个蓝色「新建」按钮（不是 + 图标）：
     类型 -> 把 Remote 改成 Local
     名称 -> 随便填
     点「选择文件」-> 选中本目录下的 mihomo.yaml
   （Local 类型不能直接粘贴内容，只能选文件）
   保存后列表里会出现这张卡片，点一下让它变成选中状态。
3. 左侧「首页」-> 打开「系统代理」开关（会要一次管理员密码）。
4. 验证：浏览器打开 https://ipinfo.io，应显示 Hong Kong。
   如果显示的是你本地城市，说明开关没生效，流量还在直连。
5. 终端也要走代理（Clash 默认混合端口 7897）：
     export https_proxy=http://127.0.0.1:7897 http_proxy=http://127.0.0.1:7897
6. 打开系统代理后浏览器若报 ERR_PROXY_CONNECTION_FAILED，多半是端口被占：
   内核日志在 ~/Library/Application Support/io.github.clash-verge-rev.clash-verge-rev/logs/sidecar/
   常见原因是上次的内核没退干净（关 App 不会杀内核），重启电脑或
   `pkill -f verge-mihomo` 后重开 App 即可。

（旧的备忘，仍然有效）
4. 终端也要走代理：
     export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890
5. 需要全局接管（含不遵守系统代理的 App）：设置里开 "Tun 模式"，
   首次会要求安装网络扩展 / 输入管理员密码。

---------------------------------------------------------------
macOS / 其他平台（sing-box）
---------------------------------------------------------------
1. 安装 sing-box 1.11+：brew install sing-box
2. TUN 需要 root：sudo sing-box run -c singbox.json
3. 不想用 TUN：删掉 inbounds 里的 tun 段，保留 mixed（127.0.0.1:7891）
   即可当普通 HTTP/SOCKS 代理使用。

---------------------------------------------------------------
排查
---------------------------------------------------------------
- 连不上先确认服务端还活着：yi status
- 竞价实例被阿里云回收后会直接消失，重跑 yi sub 拿新配置即可
- 客户端报 TLS handshake failed：多半是本地网络到 443 被封，换网络再试
""".format(
        address=info["address"],
        port=int(info["port"]),
        created=info.get("created_at", "unknown"),
    )


def write_profiles(info: dict[str, Any], label: str = "HK-Spot") -> dict[str, str]:
    """Write every client artifact into $YI_HOME/profiles and return the paths."""
    root = state.profiles_dir()
    os.makedirs(root, mode=0o700, exist_ok=True)
    link = build_link(info, label)
    artifacts = {
        "vless-link.txt": link + "\n",
        "v2rayng-subscription.txt": subscription_blob([link]) + "\n",
        "mihomo.yaml": render_mihomo(info, label),
        "singbox.json": render_singbox(info, label),
        "README.txt": render_readme(info, label),
    }
    paths: dict[str, str] = {}
    for name, content in artifacts.items():
        path = os.path.join(root, name)
        state.write_private(path, content, 0o600)
        paths[name] = path
    return paths
